#!/usr/bin/env sh

if [[ $# -ne 1 ]]; then
    echo "usage: test_me PIPEWIRE-NODE-ID"
    exit 2
fi

pw_node=${1}
GST_DEBUG=3 gst-launch-1.0 pipewiresrc path=${pw_node} ! videoconvert ! autovideosink
